Accept Person's instance or ID when pushing notification
IMGIITRoorkee/omniport-service-notifications pull request #6
Opened 2020-05-27 11:22 UTC by algomaster99

2020-05-27 12:07 UTC, pradumangoyal requested changes
Seems something wrong in the implementation of the persons

2020-05-27 12:07 UTC, pradumangoyal commented on actions.py
> +                person.id for person in persons if isinstance(person, Person)
The else condition will not be handled here, which means that only those ids will be counted for which person instance is passed.

2020-06-01 10:11 UTC, pradumangoyal approved these changes
Seems fine to me. I think it's better to support instances as well as their ids just like Django ORM handles it.

2020-06-02 06:43 UTC, algomaster99 commented
@pradumangoyal shall I pull it on the staging server?

2020-09-28 08:15 UTC, pradumangoyal approved these changes

2020-09-28 08:15 UTC, merged